image: Visual Studio 2019
platform: x64
configuration: Debug

before_build:
  - nuget restore

after_build: 7z a nightly.zip %APPVEYOR_BUILD_FOLDER%\aol_4\bin\x64\Debug\* %APPVEYOR_BUILD_FOLDER%\accounts.db

artifacts:
  path: nightly.zip
  name: nightly

deploy:
  - provider: GitHub
    tag: nightly
    release: nightly
    description: nightly
    auth_token:
      secure: selr4mVDE+XfNJ6jFTKiLTbSbDe8COHTNVRsFblZDVWS5/0qAFVym/Bcy/OoHRTT
    artifact: nightly.zip
