image: Visual Studio 2019
platform: x64
configuration: Debug

before_build:
  - nuget restore

after_build: 7z a nightly.zip %APPVEYOR_BUILD_FOLDER%\AOL_4.0_Emu\aol_4\bin\x64\Debug

artifacts:
  path: nightly.zip
  name: nightly
